{% set name = "boa-framework" %}
{% set version = "0.11.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 61530ef791595d5cbd646671eee5cd9a7c35e1e51ff39161e20d9c2144b03a0b

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools >=34.4
    - setuptools-scm
  run:
    - python >={{ python_min }}
    - pytorch >=2.0,<=3.0
    - numpy <2
    - pandas <3
    - scipy <2
    - scikit-learn <2
    - click <9
    - panel <2
    - plotly >=5.10.0
    - notebook >=5.3
    - ipywidgets >=7.5
    - ax-platform >=0.3.1,<=0.3.6
    - ruamel.yaml <1
    - attrs <24
    - jinja2 <4


test:
  imports:
    - boa
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/madeline-scyphers/boa
  summary: Bayesian Optimization for Anything
  description: |
    Bayesian Optimization for Anything: A high-level Bayesian optimization framework and model wrapping tool.
    It provides an easy-to-use interface between models and the python libraries Ax and BoTorch.
  license: MIT
  license_family: MIT
  license_file: LICENSE
  doc_url: https://pyboa.readthedocs.io
  dev_url: https://github.com/madeline-scyphers/boa

extra:
  recipe-maintainers:
    - madeline-scyphers
    - jemissik
